<a href="https://colab.research.google.com/github/rakeshedamula/pytorch_tutorial/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
# Reshape if we dont know the number of items by -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#Difference between Reshape and View

*   torch.reshape may return a copy or view of the original tensor. You cannot count on that to return a view or a copy.
*   If you need a copy use clone() if you need to use the same storage use view(). The semantics of reshape are that it may or may not share the storage and you dont know beforehand.

*   reshape() can operate on both contigious and non-contigious tensor while view() can operate only on contigious tensor







In [12]:
# Changing an item with view and reshape

In [13]:
my_torch5 = my_torch3.reshape(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch3[1] = 41
my_torch3

tensor([ 0, 41,  2,  3,  4,  5,  6,  7,  8,  9])

In [18]:
my_torch5

tensor([[ 0, 41,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [19]:
# Items returns a tensor
my_torch3[4]

tensor(4)

In [20]:
my_torch6 = my_torch3.reshape(5,2)
my_torch6

tensor([[ 0, 41],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [22]:
my_torch6[:, 1]

tensor([41,  3,  5,  7,  9])

In [23]:
my_torch6[:, 1:]

tensor([[41],
        [ 3],
        [ 5],
        [ 7],
        [ 9]])