<a href="https://colab.research.google.com/github/rakeshedamula/pytorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TENSORS

*   A torch.tensor is a multi-diemsional matrix containing elements of a single data type
*   Similar to Numpy Arrays, but works better on GPUs (vs regular CPUs)

*   Default data type is float32
*   More suitable for deep learning





In [1]:
import torch
import numpy as np

#Lists

In [2]:
my_list = [[1,2,3,4], [5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

#Numpy Arrays

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.28631145, 0.35942839, 0.53837947, 0.97050177],
       [0.49462848, 0.50437245, 0.44079448, 0.88054158],
       [0.71994625, 0.29827632, 0.4493125 , 0.12619363]])

In [8]:
np1.dtype

dtype('float64')

#Tensors

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5721,  0.6385, -1.3907,  1.5420],
        [-0.4454, -1.6456,  0.2456, -1.0412],
        [ 1.4984, -1.2506,  0.2468, -1.0654]])

In [10]:
tensor_2d.dtype

torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
# Create tensor out of numpy array
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.2863, 0.3594, 0.5384, 0.9705],
        [0.4946, 0.5044, 0.4408, 0.8805],
        [0.7199, 0.2983, 0.4493, 0.1262]], dtype=torch.float64)